version: "2.1"

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PSQL_DATABASE: ${PSQL_NAME}
      PSQL_USER: ${PSQL_USERNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE_HOST: db
      PSQL_DATABASE_PORT: 5432
      REDIS_HOST: "redis://redis:6379/0"
      TZ: ${TZ}
    restart: always
    volumes:
      - ./carwings/settings.py:/app/carwings/settings.py # pass only settings.py, other files need to be added separately
      - ./staticfiles/:/app/staticfiles/
      - ./mediafiles/:/app/mediafiles/
      - ./logs/:/app/logs/
    ports:
      - "${BACKEND_PORT}:80"
      - "${TCPSERVER_PORT}:55230"
    cap_drop:
        - ALL
    user: "5000:5000"
    security_opt:
        - no-new-privileges:true

  db:
    image: postgres:18
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
	cap_drop:
		- ALL
	cap_add:
		- CHOWN
		- DAC_OVERRIDE
		- FOWNER
		- SETUID
		- SETGID

  redis:
    image: redis:7
    security_opt:
        - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID


volumes:
  psql_data:
